version: '3'
services:
  jenkins:
    build: .
    container_name: jenkins
    user: jenkins
    hostname: jenkins.devops
    volumes:
      - ./vol_jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      JENKINS_HOST_HOME: "./vol_jenkins"
    ports:
      - "4080:8080"
      - "51000:50000"
      - "5100:5000"
    networks:
      - network_devops

  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    ports:
      - "9100:9000"
      - "9092:9092"
    networks:
      - network_devops

networks:
  network_devops:
    external:
      name: "network_devops"
